version: "3"

services:
  app:
    build: .
    # dockerfile: Dockerfile
    environment:
      - TIME_ZONE=Europe/Zurich
      #- DB_HOST=db
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
